// Code generated from cloudflare/security-audit-skill class names; DO NOT EDIT BY HAND.
package coveragecatalog

var skillClasses = []ClassDefinition{
	{Domain: "Core", Source: "ATTACK-CLASSES.md", Name: "Access control"},
	{Domain: "Core", Source: "ATTACK-CLASSES.md", Name: "Business logic"},
	{Domain: "Core", Source: "ATTACK-CLASSES.md", Name: "Chained vulnerabilities and trust boundaries"},
	{Domain: "Core", Source: "ATTACK-CLASSES.md", Name: "Cryptography and secrets"},
	{Domain: "Core", Source: "ATTACK-CLASSES.md", Name: "Feature abuse and data leakage"},
	{Domain: "Core", Source: "ATTACK-CLASSES.md", Name: "Injection"},
	{Domain: "Core", Source: "ATTACK-CLASSES.md", Name: "Obvious things"},
	{Domain: "Core", Source: "ATTACK-CLASSES.md", Name: "Resource and file handling"},
	{Domain: "Core", Source: "ATTACK-CLASSES.md", Name: "Wildcard"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "API-key exposure and unsafe transport"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "API-key scope and resource binding"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "Account linking and identity collision"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "Cache deception and private-response caching"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "Certificate lifecycle fallback"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "Cookie scope and transport"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "Host and forwarded-header trust"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "JWT verification and claim binding"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "MFA enrollment and assurance downgrade"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "OAuth/OIDC request and callback binding"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "Ordinary CSRF"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "Password reset and broader recovery"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "Request framing and desynchronization"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "Response-header injection"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "SAML signed-object and assertion binding"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "Session fixation and invalidation"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "Step-up binding and bypass"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "Web cache poisoning through unkeyed input"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "WebAuthn and passkey verification"},
	{Domain: "HTTP, web and authentication", Source: "WEB-PROTOCOL-AND-AUTH.md", Name: "mTLS peer and application-identity confusion"},
	{Domain: "Client-side and browser", Source: "CLIENT-SIDE.md", Name: "Browser-storage disclosure and stale authorization"},
	{Domain: "Client-side and browser", Source: "CLIENT-SIDE.md", Name: "Clickjacking"},
	{Domain: "Client-side and browser", Source: "CLIENT-SIDE.md", Name: "Client-side navigation confusion"},
	{Domain: "Client-side and browser", Source: "CLIENT-SIDE.md", Name: "Credentialed CORS trust"},
	{Domain: "Client-side and browser", Source: "CLIENT-SIDE.md", Name: "Cross-context storage and broadcast confusion"},
	{Domain: "Client-side and browser", Source: "CLIENT-SIDE.md", Name: "Cross-site WebSocket request use"},
	{Domain: "Client-side and browser", Source: "CLIENT-SIDE.md", Name: "DOM clobbering"},
	{Domain: "Client-side and browser", Source: "CLIENT-SIDE.md", Name: "DOM-based XSS"},
	{Domain: "Client-side and browser", Source: "CLIENT-SIDE.md", Name: "Prototype pollution and gadget chain"},
	{Domain: "Client-side and browser", Source: "CLIENT-SIDE.md", Name: "Service-worker cache and identity confusion"},
	{Domain: "Client-side and browser", Source: "CLIENT-SIDE.md", Name: "Service-worker registration and scope takeover"},
	{Domain: "Client-side and browser", Source: "CLIENT-SIDE.md", Name: "Window and opener state disclosure"},
	{Domain: "Client-side and browser", Source: "CLIENT-SIDE.md", Name: "XS-Leaks and cross-origin state oracles"},
	{Domain: "Client-side and browser", Source: "CLIENT-SIDE.md", Name: "`postMessage` origin and source trust"},
	{Domain: "Resource exhaustion and availability", Source: "RESOURCE-EXHAUSTION-AND-AVAILABILITY.md", Name: "Database and downstream query amplification"},
	{Domain: "Resource exhaustion and availability", Source: "RESOURCE-EXHAUSTION-AND-AVAILABILITY.md", Name: "Decompression and representation amplification"},
	{Domain: "Resource exhaustion and availability", Source: "RESOURCE-EXHAUSTION-AND-AVAILABILITY.md", Name: "Detached work after cancellation"},
	{Domain: "Resource exhaustion and availability", Source: "RESOURCE-EXHAUSTION-AND-AVAILABILITY.md", Name: "File descriptor, handle, and temporary-resource leaks"},
	{Domain: "Resource exhaustion and availability", Source: "RESOURCE-EXHAUSTION-AND-AVAILABILITY.md", Name: "Poison-record and head-of-line blocking"},
	{Domain: "Resource exhaustion and availability", Source: "RESOURCE-EXHAUSTION-AND-AVAILABILITY.md", Name: "Pre-authentication work imbalance"},
	{Domain: "Resource exhaustion and availability", Source: "RESOURCE-EXHAUSTION-AND-AVAILABILITY.md", Name: "Quota-accounting scope and reset gaps"},
	{Domain: "Resource exhaustion and availability", Source: "RESOURCE-EXHAUSTION-AND-AVAILABILITY.md", Name: "Reachable fatal error or deadlock"},
	{Domain: "Resource exhaustion and availability", Source: "RESOURCE-EXHAUSTION-AND-AVAILABILITY.md", Name: "Retry storm and fail-open amplification"},
	{Domain: "Resource exhaustion and availability", Source: "RESOURCE-EXHAUSTION-AND-AVAILABILITY.md", Name: "Superlinear parsing, matching, or evaluation"},
	{Domain: "Resource exhaustion and availability", Source: "RESOURCE-EXHAUSTION-AND-AVAILABILITY.md", Name: "Unbounded buffering and cardinality"},
	{Domain: "Resource exhaustion and availability", Source: "RESOURCE-EXHAUSTION-AND-AVAILABILITY.md", Name: "Unsafe recovery and capacity rollback"},
	{Domain: "Resource exhaustion and availability", Source: "RESOURCE-EXHAUSTION-AND-AVAILABILITY.md", Name: "Worker, pool, and priority starvation"},
	{Domain: "Protocols, RPC and messaging", Source: "PROTOCOLS-RPC-AND-MESSAGING.md", Name: "Acknowledgment/commit ordering defects"},
	{Domain: "Protocols, RPC and messaging", Source: "PROTOCOLS-RPC-AND-MESSAGING.md", Name: "Callback and reply-correlation confusion"},
	{Domain: "Protocols, RPC and messaging", Source: "PROTOCOLS-RPC-AND-MESSAGING.md", Name: "Dead-letter, retry, and diagnostic disclosure"},
	{Domain: "Protocols, RPC and messaging", Source: "PROTOCOLS-RPC-AND-MESSAGING.md", Name: "Duplicate delivery and idempotency gaps"},
	{Domain: "Protocols, RPC and messaging", Source: "PROTOCOLS-RPC-AND-MESSAGING.md", Name: "Envelope and payload identity mismatch"},
	{Domain: "Protocols, RPC and messaging", Source: "PROTOCOLS-RPC-AND-MESSAGING.md", Name: "Interceptor and method-path inconsistency"},
	{Domain: "Protocols, RPC and messaging", Source: "PROTOCOLS-RPC-AND-MESSAGING.md", Name: "Message boundary and canonicalization disagreement"},
	{Domain: "Protocols, RPC and messaging", Source: "PROTOCOLS-RPC-AND-MESSAGING.md", Name: "Out-of-order and stale message acceptance"},
	{Domain: "Protocols, RPC and messaging", Source: "PROTOCOLS-RPC-AND-MESSAGING.md", Name: "Partial multi-consumer transitions"},
	{Domain: "Protocols, RPC and messaging", Source: "PROTOCOLS-RPC-AND-MESSAGING.md", Name: "Peer identity to application-principal confusion"},
	{Domain: "Protocols, RPC and messaging", Source: "PROTOCOLS-RPC-AND-MESSAGING.md", Name: "Per-item and streaming authorization gaps"},
	{Domain: "Protocols, RPC and messaging", Source: "PROTOCOLS-RPC-AND-MESSAGING.md", Name: "Topic, routing-key, and subscription scope gaps"},
	{Domain: "Protocols, RPC and messaging", Source: "PROTOCOLS-RPC-AND-MESSAGING.md", Name: "Union, enum, and default confusion"},
	{Domain: "Protocols, RPC and messaging", Source: "PROTOCOLS-RPC-AND-MESSAGING.md", Name: "Untrusted producer treated as control plane"},
	{Domain: "Data isolation and lifecycle", Source: "DATA-ISOLATION-AND-LIFECYCLE.md", Name: "Analytics, logs, traces, and diagnostics as alternate readers"},
	{Domain: "Data isolation and lifecycle", Source: "DATA-ISOLATION-AND-LIFECYCLE.md", Name: "Backup and replication boundary drift"},
	{Domain: "Data isolation and lifecycle", Source: "DATA-ISOLATION-AND-LIFECYCLE.md", Name: "Blob and signed-reference overreach"},
	{Domain: "Data isolation and lifecycle", Source: "DATA-ISOLATION-AND-LIFECYCLE.md", Name: "Composite-key and namespace collision"},
	{Domain: "Data isolation and lifecycle", Source: "DATA-ISOLATION-AND-LIFECYCLE.md", Name: "Enumeration and aggregate oracles"},
	{Domain: "Data isolation and lifecycle", Source: "DATA-ISOLATION-AND-LIFECYCLE.md", Name: "Export and backup scope expansion"},
	{Domain: "Data isolation and lifecycle", Source: "DATA-ISOLATION-AND-LIFECYCLE.md", Name: "Import and restore authority expansion"},
	{Domain: "Data isolation and lifecycle", Source: "DATA-ISOLATION-AND-LIFECYCLE.md", Name: "Migration default and ownership confusion"},
	{Domain: "Data isolation and lifecycle", Source: "DATA-ISOLATION-AND-LIFECYCLE.md", Name: "Missing tenant or owner enforcement"},
	{Domain: "Data isolation and lifecycle", Source: "DATA-ISOLATION-AND-LIFECYCLE.md", Name: "Policy and query disagreement"},
	{Domain: "Data isolation and lifecycle", Source: "DATA-ISOLATION-AND-LIFECYCLE.md", Name: "Restore reintroduces invalid state"},
	{Domain: "Data isolation and lifecycle", Source: "DATA-ISOLATION-AND-LIFECYCLE.md", Name: "Retention and queued-work overrun"},
	{Domain: "Data isolation and lifecycle", Source: "DATA-ISOLATION-AND-LIFECYCLE.md", Name: "Search, cache, and index ACL drift"},
	{Domain: "Data isolation and lifecycle", Source: "DATA-ISOLATION-AND-LIFECYCLE.md", Name: "Soft-delete and tombstone bypass"},
	{Domain: "Data isolation and lifecycle", Source: "DATA-ISOLATION-AND-LIFECYCLE.md", Name: "Stale authorization and derived copy use"},
	{Domain: "Supply chain and release", Source: "SUPPLY-CHAIN-AND-RELEASE.md", Name: "Automation identity overreach"},
	{Domain: "Supply chain and release", Source: "SUPPLY-CHAIN-AND-RELEASE.md", Name: "Build-context inclusion"},
	{Domain: "Supply chain and release", Source: "SUPPLY-CHAIN-AND-RELEASE.md", Name: "Build-to-promotion substitution"},
	{Domain: "Supply chain and release", Source: "SUPPLY-CHAIN-AND-RELEASE.md", Name: "Cache, artifact, and workspace trust mixing"},
	{Domain: "Supply chain and release", Source: "SUPPLY-CHAIN-AND-RELEASE.md", Name: "Dependency source and namespace confusion"},
	{Domain: "Supply chain and release", Source: "SUPPLY-CHAIN-AND-RELEASE.md", Name: "Generated-source and codegen provenance gaps"},
	{Domain: "Supply chain and release", Source: "SUPPLY-CHAIN-AND-RELEASE.md", Name: "Mutable and unbound build inputs"},
	{Domain: "Supply chain and release", Source: "SUPPLY-CHAIN-AND-RELEASE.md", Name: "Plugin and extension trust expansion"},
	{Domain: "Supply chain and release", Source: "SUPPLY-CHAIN-AND-RELEASE.md", Name: "Release authorization and signing-policy gaps"},
	{Domain: "Supply chain and release", Source: "SUPPLY-CHAIN-AND-RELEASE.md", Name: "Untrusted code in a privileged workflow"},
	{Domain: "Supply chain and release", Source: "SUPPLY-CHAIN-AND-RELEASE.md", Name: "Update metadata and rollback confusion"},
	{Domain: "Supply chain and release", Source: "SUPPLY-CHAIN-AND-RELEASE.md", Name: "Workflow command and expression confusion"},
	{Domain: "Cloud and deployment", Source: "CLOUD-AND-DEPLOYMENT.md", Name: "Admission and policy path inconsistency"},
	{Domain: "Cloud and deployment", Source: "CLOUD-AND-DEPLOYMENT.md", Name: "Application authorization delegated to cloud metadata"},
	{Domain: "Cloud and deployment", Source: "CLOUD-AND-DEPLOYMENT.md", Name: "Credential renewal and outage fallback"},
	{Domain: "Cloud and deployment", Source: "CLOUD-AND-DEPLOYMENT.md", Name: "Cross-account or cross-tenant role confusion"},
	{Domain: "Cloud and deployment", Source: "CLOUD-AND-DEPLOYMENT.md", Name: "Edge/runtime boundary mismatch"},
	{Domain: "Cloud and deployment", Source: "CLOUD-AND-DEPLOYMENT.md", Name: "Event-source identity confusion"},
	{Domain: "Cloud and deployment", Source: "CLOUD-AND-DEPLOYMENT.md", Name: "Host or control-plane capability exposure"},
	{Domain: "Cloud and deployment", Source: "CLOUD-AND-DEPLOYMENT.md", Name: "Metadata and internal-service reachability"},
	{Domain: "Cloud and deployment", Source: "CLOUD-AND-DEPLOYMENT.md", Name: "Namespace and label trust confusion"},
	{Domain: "Cloud and deployment", Source: "CLOUD-AND-DEPLOYMENT.md", Name: "Object and signed-URL policy confusion"},
	{Domain: "Cloud and deployment", Source: "CLOUD-AND-DEPLOYMENT.md", Name: "Secret exposure across workload boundaries"},
	{Domain: "Cloud and deployment", Source: "CLOUD-AND-DEPLOYMENT.md", Name: "Security-control precedence drift"},
	{Domain: "Cloud and deployment", Source: "CLOUD-AND-DEPLOYMENT.md", Name: "Trusted-proxy and mesh identity bypass"},
	{Domain: "Cloud and deployment", Source: "CLOUD-AND-DEPLOYMENT.md", Name: "Unexpected service or management-plane reachability"},
	{Domain: "Cloud and deployment", Source: "CLOUD-AND-DEPLOYMENT.md", Name: "Workload identity overreach"},
	{Domain: "AI, LLM and agents", Source: "AI-AND-LLM.md", Name: "Action-confirmation and approval binding"},
	{Domain: "AI, LLM and agents", Source: "AI-AND-LLM.md", Name: "Cross-session or cross-tenant context bleed"},
	{Domain: "AI, LLM and agents", Source: "AI-AND-LLM.md", Name: "Excessive agency and confused-deputy authority"},
	{Domain: "AI, LLM and agents", Source: "AI-AND-LLM.md", Name: "Indirect injection through retrieved or ingested content"},
	{Domain: "AI, LLM and agents", Source: "AI-AND-LLM.md", Name: "Insecure output rendering"},
	{Domain: "AI, LLM and agents", Source: "AI-AND-LLM.md", Name: "MCP metadata and schema as policy"},
	{Domain: "AI, LLM and agents", Source: "AI-AND-LLM.md", Name: "MCP server and tool identity confusion"},
	{Domain: "AI, LLM and agents", Source: "AI-AND-LLM.md", Name: "Persistent memory poisoning"},
	{Domain: "AI, LLM and agents", Source: "AI-AND-LLM.md", Name: "Prompt role and provenance confusion"},
	{Domain: "AI, LLM and agents", Source: "AI-AND-LLM.md", Name: "Sensitive context extraction"},
	{Domain: "AI, LLM and agents", Source: "AI-AND-LLM.md", Name: "Sub-agent and MCP trust inheritance"},
	{Domain: "AI, LLM and agents", Source: "AI-AND-LLM.md", Name: "Tool-argument injection into a downstream sink"},
	{Domain: "AI, LLM and agents", Source: "AI-AND-LLM.md", Name: "Tool-schema and dispatcher disagreement"},
	{Domain: "AI, LLM and agents", Source: "AI-AND-LLM.md", Name: "Unbounded delegated action loops"},
	{Domain: "Desktop, mobile and local IPC", Source: "DESKTOP-MOBILE-AND-LOCAL-IPC.md", Name: "Account switch, logout, and device restore leakage"},
	{Domain: "Desktop, mobile and local IPC", Source: "DESKTOP-MOBILE-AND-LOCAL-IPC.md", Name: "App and account handoff confusion"},
	{Domain: "Desktop, mobile and local IPC", Source: "DESKTOP-MOBILE-AND-LOCAL-IPC.md", Name: "Claimed principal versus channel identity"},
	{Domain: "Desktop, mobile and local IPC", Source: "DESKTOP-MOBILE-AND-LOCAL-IPC.md", Name: "Credential-store and local-secret boundary mismatch"},
	{Domain: "Desktop, mobile and local IPC", Source: "DESKTOP-MOBILE-AND-LOCAL-IPC.md", Name: "Custom-scheme and deep-link ambiguity"},
	{Domain: "Desktop, mobile and local IPC", Source: "DESKTOP-MOBILE-AND-LOCAL-IPC.md", Name: "Exported service, activity, receiver, or provider overreach"},
	{Domain: "Desktop, mobile and local IPC", Source: "DESKTOP-MOBILE-AND-LOCAL-IPC.md", Name: "File-open and intent authority confusion"},
	{Domain: "Desktop, mobile and local IPC", Source: "DESKTOP-MOBILE-AND-LOCAL-IPC.md", Name: "IPC lifecycle and correlation confusion"},
	{Domain: "Desktop, mobile and local IPC", Source: "DESKTOP-MOBILE-AND-LOCAL-IPC.md", Name: "IPC peer-authentication gaps"},
	{Domain: "Desktop, mobile and local IPC", Source: "DESKTOP-MOBILE-AND-LOCAL-IPC.md", Name: "Install, update, and repair path trust"},
	{Domain: "Desktop, mobile and local IPC", Source: "DESKTOP-MOBILE-AND-LOCAL-IPC.md", Name: "Local file ownership and TOCTOU"},
	{Domain: "Desktop, mobile and local IPC", Source: "DESKTOP-MOBILE-AND-LOCAL-IPC.md", Name: "Navigation-origin to bridge confusion"},
	{Domain: "Desktop, mobile and local IPC", Source: "DESKTOP-MOBILE-AND-LOCAL-IPC.md", Name: "Over-broad native bridge capabilities"},
	{Domain: "Desktop, mobile and local IPC", Source: "DESKTOP-MOBILE-AND-LOCAL-IPC.md", Name: "Pending-action and user-presence confusion"},
	{Domain: "Desktop, mobile and local IPC", Source: "DESKTOP-MOBILE-AND-LOCAL-IPC.md", Name: "Privileged helper as confused deputy"},
	{Domain: "Desktop, mobile and local IPC", Source: "DESKTOP-MOBILE-AND-LOCAL-IPC.md", Name: "Webview file and universal access"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "Integer overflow, underflow, truncation, and signedness"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "JIT and generated-code consistency"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "Layout, alignment, and enum disagreement"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "Library, plugin, and executable search-order trust"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "Lock-order, deadlock, and starvation"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "Malformed binary metadata and relocation handling"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "Missing artifact identity or signature binding"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "Out-of-bounds read or write"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "Pointer-length and ownership contract mismatch"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "Privileged object lifecycle and dispatch consistency"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "Reference-count and ownership races"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "Shared-state races and TOCTOU"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "Type confusion and invalid downcast"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "Under-authorized powerful interfaces"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "Uninitialized or partially initialized data"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "Unit and pointer-depth confusion"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "Unload, reload, and teardown safety"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "Unwind, exception, and thread-affinity violations"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "Use-after-free, stale view, and double free"},
	{Domain: "Memory safety, binary and kernel", Source: "MEMORY-SAFETY-AND-BINARY.md", Name: "User-copy bounds and repeated reads"},
}
